- name: Hello World Sample
  hosts: all
  gather_facts: True
  
  tasks:
    - name: get disk total
      shell: df --total -h|grep total |awk '{print $2}'
      register: disk_total
    - debug: msg="{{disk_total}}"
